### ISSUE TITLE
Refence file from another project cause issue with name space

### ISSUE THREAD

**Issue by knopa** [kl1mm/localize#7]
i18n - Project
<AdditionalFiles Include="..\AnotherProject\folder\folder\file.json"

Generate - **.i18n....**

empty namespaces

Prodbably good idea add parameter in AdditionalFiles to force name space and file name
same issue if you want to use only localization.en-US.json it do in lowercase with culture

**Comment by kl1mm** [comment]
Hi @knopa,
sry for the long delay.

Please have a look to the new version [v0.8.3](https://github.com/kl1mm/localize/releases/tag/v0.8.3). 
It possible now to set the generated namespace name and class / filename via parameter in die AdditionalFiles-Tag.

see: [README.md section: v0.8](https://github.com/kl1mm/localize/blob/develop/README.md#from-version-08)

please let me know if this solves your problems.
greetings

**Comment by knopa** [comment]
hi @kl1mm 

Thanks for update 

with ` localization.en-US.json` now it's generate with class name but shows error from `localization.en-US.g.cs`
with another file name 

```
<AdditionalFiles Include="$(SolutionDir)\AnotherProject\i18n\localization.en-US.json" 
                     NamespaceName="Test.i18n"
                     ClassName="MyLocale"/>
```
![image](https://user-images.githubusercontent.com/1783681/221514731-f0565124-63b2-41a8-a564-e1494684bb8b.png)
Errors shows from original file name
![image](https://user-images.githubusercontent.com/1783681/221514835-0f3b8da6-593c-4df7-b763-dc65bc660f17.png)

If I rename `localization.en-US.json` to `MyLocale.json` as example I will get another issue
![image](https://user-images.githubusercontent.com/1783681/221515147-45944b98-4b0a-4684-9747-50fa957d22f6.png)

If i use directly generated code - it works fine.
Sounds like it have one more file underhood which mess with outcome file and build process

**Comment by kl1mm** [comment]
hi @knopa,
can u provide me with a little reprocudable sample? Otherwise it is hard for me to understand your exact issue.

**Comment by knopa** [comment]
@kl1mm 
I have attached sample.
[testKli.zip](https://github.com/kl1mm/localize/files/10838303/testKli.zip)

**Comment by kl1mm** [comment]
hi @knopa,
after a short investigation of your issue I found out that when including the AdditionalFile the path is not fully compliant. 

This unfortunately leads to a misbehavior that I will try to improve!

But for you it should be easy to solve the issue because the variable $(SoultionDir) already contains a "\\" witch means you can simply remove it in the path and then it hopefully works for you.

![image](https://user-images.githubusercontent.com/18304813/221602723-2be8d892-8bb5-45a9-96e6-f9aba6de6b79.png)

$(SolutionDir)\src\test.json => C:\slnDir\\\src\test.json 🐞
$(SolutionDir)src\test.json => C:\slnDir\src\test.json 👍

greetings

**Comment by knopa** [comment]
@kl1mm it's really tricky issue. With your workaround works fine.

You are awesome.

**Comment by kl1mm** [comment]
I am glad that I could help you. I would appriciate it, if you would give me a star for the project. :)
greetings
